### ISSUE TITLE
Bug with Bungeecord - doesn't transfer players on fallback servers

### ISSUE THREAD

**Issue by morjanmihail** [brunyman/Essentials-MySQL-Storage-Extension#3]
Hello @brunyman,

   There is a problem with bungeecord network. If you're trying to restart a spigot server from a bungeecord network, it will not teleport the players on a fallback server but will throw them out with a message like this: 

![image](https://user-images.githubusercontent.com/13481999/90659158-073cb680-e24d-11ea-9c78-298df6be9121.png)

   If I deactivate the plugin everything works normal, as expected.

   More details about the environment:

**Bungeecord (Last stable version) with plugins **:
AuthMeBungee
BungeeEssentials
BungeeTabListPlus-3.3.4
LuckPerms-Bungee-5.1.86
nuvotifier-2.7.1
ServerListPlus-3.4.8
SkinsRestorer

**Paper Spigot 1.16.1 (v.135) with plugins: ** 
AuthMe
BungeeTabListPlus_BukkitBridge-3.3.4
Citizens-2.0.27
EssentialsX-2.18.0.0
EssentialsMysqlStorage-1.22.1
LuckPerms-Bukkit-5.1.26
Multiverse-Core-4.1.0
Multiverse-Inventories-3.0.0
nuvotifier-2.7.1
PlaceholderAPI-2.10.9
SkinsRestorer
Vault
VotingPlugin
worldedit-bukkit-7.2.0
worldguard-bukkit-7.0.3
   

Thanks in advance for your help,
Mihai

**Comment by brunyman** [comment]
I don't understand how, as this does nothing else on player disconnect then to save his data

**Comment by Alexz1008** [comment]
I assume it's because on server stop, the command /ems saveandkick is automatically run

**Comment by brunyman** [comment]
**Added config option to disable players being kicked when the saveandkick command is executed so players will be moved when the server closes to the bungee fallback server**
